In [126]:
import json

def monthly_salary():
    with open('employes_data.json', 'r') as file_json:
        data_employees = json.load(file_json)

    TechCorp = data_employees["TechCorp"]

    DesignWorks = data_employees["DesignWorks"]

    ProjectLead = data_employees["ProjectLead"]

    print(data_employees.keys())


    print(TechCorp)
    print(DesignWorks)
    print(ProjectLead)

    def calculate_monthly_salary(employee):
        contract_hours = employee['contract_hours']
        worked_hours = employee['worked_hours']
        hourly_rate = employee['hourly_rate']

        if worked_hours > contract_hours:
            overtime_hours = worked_hours - contract_hours
            overtime_rate = hourly_rate * 1.5
            salary = contract_hours * hourly_rate + overtime_hours * overtime_rate
        else:
            salary = worked_hours * hourly_rate

        return salary
    
    def salary_employees():
        for filliale, employees in data_employees.item:
            for employee in employees:
                name = employee['name']
                job = employee['job']
                salary = calculate_monthly_salary(employee)

            return {name: employee['name'], job: employee['job'], salary: calculate_monthly_salary(employee)}
        
name, job, salary = salary_employees()

    def employee_statistic(salary_employees):
        for filliale in data_employees:
            mean_salary = sum(salary_employees) / len(salary_employees)
            maximum_salary = max(salary_employees)
            minimum_salary = min(salary_employees)

        return mean_salary, maximum_salary, minimum_salary

   
    
for i in range(len[salary]):
        print(f"name: {name[i]}| job: {job[i]}|Salaire mensuel: {salary_employees * 4}")

    monthly_salary()

NameError: name 'data_employees' is not defined

In [104]:
for i in range(len(salary)):
    print(f"name: {name[i]}| job: {job[i]}|Salaire mensuel: {salary_employees * 4}")

NameError: name 'salary' is not defined

In [ ]:

 def salary_employees():
        for filliale, employees in data_employees.item:
            for employee in employees:
                name = employee['name']
                job = employee['job']
                salary = calculate_monthly_salary(employee)

            print(f"Name: {name}, Job: {job}, Salary: {salary}")

In [ ]:
for filiales, employes in data.items():
    entreprise[filiales] = []
    for employe in employes:
        new_employe= {
          "name":employe['name'],
          "job": employe['job'],
          "salaire": calcul_des_salaires_mensuels(employe)
        }
        entreprise[filiales].append(new_employe)
print(entreprise['TechCorp'])

In [ ]:
 my_dict = []

    for filiales, employees in data.items():
        my_dict[filiales] = []
        for employe in employees:
            new_employe= {
            "name":employe['name'],
            "job": employe['job'],
            "salary": calcul_des_salaires_mensuels(employe)
            }
            my_dict[filiales].append(new_employe)
    print(my_dict['TechCorp'])

BON CODE

In [160]:
import json

def monthly_salary():
    with open('employes_data.json', 'r') as file_json:
        data_employees = json.load(file_json)

    def calculate_monthly_salary(employee):
        contract_hours = employee['contract_hours']
        weekly_hours_worked = employee['weekly_hours_worked']
        hourly_rate = employee['hourly_rate']

        if weekly_hours_worked > contract_hours:
            overtime_hours = weekly_hours_worked - contract_hours
            overtime_rate = hourly_rate * 1.5
            salary = contract_hours * hourly_rate + overtime_hours * overtime_rate
        else:
            salary = weekly_hours_worked * hourly_rate

        return salary

    def salary_employees():
        employees_salaries = []
        for filliale, employees in data_employees.items():
            for employee in employees:
                name = employee['name']
                job = employee['job']
                salary = calculate_monthly_salary(employee)
                employees_salaries.append({
                    'name': name,
                    'job': job,
                    'salary': salary
                })
        return employees_salaries
    
    employees_salaries = salary_employees()

    for employee in employees_salaries:
        print(f"{employee['name']:<20} |{employee['job']:<20} |{employee['salary']:<20.2f}")

def calculate_statistics(employees):
    salaries = [employee['salary'] for employee in employees]
    mean_salary = sum(salary_employees) / len(salary_employees)
    maximum_salary = max(salary_employees)
    minimum_salary = min(salary_employees)
    return mean_salary, maximum_salary, minimum_salary

def group_employees_by_filliale(employees_salaries):
    filliales = {}
    for employee in employees_salaries:
        filliale = employee['filliale']
        if filliale in filliales:
            filliales[filliale].append(employee)
        else:
            filliales[filliale] = [employee]

    print("\nStatistiques des salaires :")
    print(f"Salaire moyen: {mean_salary:.2f}")
    print(f"Salaire maximum: {max_salary:.2f}")
    print(f"Salaire minimum: {min_salary:.2f}")

    filliales = group_employees_by_filliale(employees_salaries)

    print("\nEmployés par filiale :")
    for filliale, employees in filliales.items():
        print(f"\nFiliale: {filliale}")
        for employee in employees:
            print(f" - {employee['name']} ({employee['job']}) : {employee['salary']:.2f}")


monthly_salary()

Helen                |Chef de projet       |2375.00
Quincy               |Testeur              |1456.00
Fred                 |Manager              |1815.00
Steve                |Chef de projet       |1600.00
Linda                |Chef de projet       |1700.00
Bob                  |Analyste             |1400.00
Steve                |Chef de projet       |2825.00
Karen                |Développeur          |1155.00
Paul                 |Designer             |900.00
Bob                  |Développeur          |1907.50
Bob                  |Manager              |2750.00
Mike                 |Testeur              |924.00
Mike                 |Chef de projet       |2225.00
Charlie              |Chef de projet       |1600.00
Helen                |Testeur              |1526.00
Jack                 |Analyste             |1520.00
Emma                 |Designer             |1020.00
Ian                  |Chef de projet       |1900.00
Tina                 |Testeur              |1526.00
Oliver               |Chef de projet       |2675.00
Jack                 |Designer             |990.00
Oliver               |Manager              |2612.50
Rachel               |Testeur              |1064.00
Ian                  |Testeur              |1288.00
Jack                 |Chef de projet       |1900.00
Rachel               |Analyste             |1280.00
Helen                |Développeur          |1330.00
George               |Développeur          |1050.00
Rachel               |Testeur              |1526.00
Emma                 |Chef de projet       |2375.00
Mike                 |Manager              |1760.00
Ian                  |Chef de projet       |2050.00
Bob                  |Chef de projet       |2500.00
Fred                 |Testeur              |1498.00
Mike                 |Développeur          |1120.00
Oliver               |Chef de projet       |1975.00
Tina                 |Manager              |2035.00
Linda                |Testeur              |1120.00
Rachel               |Designer             |1635.00
Bob                  |Manager              |2832.50
Steve                |Chef de projet       |2375.00
Jack                 |Chef de projet       |1550.00
Jack                 |Designer             |1545.00
Charlie              |Manager              |2530.00
Oliver               |Développeur          |1225.00
Nina                 |Analyste             |1900.00
Steve                |Designer             |1335.00
Linda                |Développeur          |1277.50
Jack                 |Testeur              |1442.00
Charlie              |Chef de projet       |2125.00

In [152]:
print("\nStatistiques des salaires :")
print(f"Salaire moyen: {mean_salary:.2f}")
print(f"Salaire maximum: {max_salary:.2f}")
print(f"Salaire minimum: {min_salary:.2f}")

filliales = group_employees_by_filliale(employees_salaries)

print("\nEmployés par filliale :")
for filliale, employees in filliales.items():
    print(f"\nFilliale: {filliale}")
    for employee in employees:
        print(f" - {employee['name']} ({employee['job']}) : {employee['salary']:.2f}")

Statistiques des salaires :

NameError: name 'mean_salary' is not defined

In [ ]:
print(f"{'Nom':<20} |{'Job':<20} |{'Salaire Mensuel (€)':<20}\n{'='*60}")
for employee in employees_salaries: print(f"{employee['name']:<20} |{employee['job']:<20} |{employee['salary']:<20.2f}")


monthly_salary()

In [142]:
def calculate_statistics(employees):
    salaries = [employee['salary'] for employee in employees]
    mean_salary = sum(salary_employees) / len(salary_employees)
    maximum_salary = max(salary_employees)
    minimum_salary = min(salary_employees)
    return mean_salary, maximum_salary, minimum_salary

In [141]:
def group_employees_by_filliale(employees_salaries):
    filliales = {}
    for employee in employees_salaries:
        filliale = employee['filliale']
        if filliale in filliales:
            filliales[filliale].append(employee)
        else:
            filliales[filliale] = [employee]

In [150]:
print(f"\nStatistiques pour la filiale '{filliale}' :")
        print(f"Salaire moyen : {stats['average']:.2f} €")
        print(f"Salaire le plus élevé : {stats['highest']:.2f} €")
        print(f"Salaire le plus bas : {stats['lowest']:.2f} €")

IndentationError: unexpected indent (3913041644.py, line 2)

In [156]:
import json

def monthly_salary():
    with open('employes_data.json', 'r') as file_json:
        data_employees = json.load(file_json)

    def calculate_monthly_salary(employee):
        contract_hours = employee['contract_hours']
        weekly_hours_worked = employee['weekly_hours_worked']
        hourly_rate = employee['hourly_rate']

        if weekly_hours_worked > contract_hours:
            overtime_hours = weekly_hours_worked - contract_hours
            overtime_rate = hourly_rate * 1.5
            salary = contract_hours * hourly_rate + overtime_hours * overtime_rate
        else:
            salary = weekly_hours_worked * hourly_rate

        return salary

    def salary_employees():
        employees_salaries = []
        for filliale, employees in data_employees.items():
            for employee in employees:
                name = employee['name']
                job = employee['job']
                # Vérification si la clé 'filliale' existe, sinon valeur par défaut
                filliale = employee.get('filliale', 'Inconnue')  
                salary = calculate_monthly_salary(employee)
                employees_salaries.append({
                    'name': name,
                    'job': job,
                    'filliale': filliale,
                    'salary': salary
                })
        return employees_salaries
    
    employees_salaries = salary_employees()

    for employee in employees_salaries:
        print(f"{employee['name']:<20} |{employee['job']:<20} |{employee['salary']:<20.2f}")

    return employees_salaries

def calculate_statistics(employees_salaries):
    salaries = [employee['salary'] for employee in employees_salaries]
    mean_salary = sum(salaries) / len(salaries)
    maximum_salary = max(salaries)
    minimum_salary = min(salaries)
    return mean_salary, maximum_salary, minimum_salary

def group_employees_by_filliale(employees_salaries):
    filliales = {}
    for employee in employees_salaries:
        filliale = employee['filliale']
        if filliale in filliales:
            filliales[filliale].append(employee)
        else:
            filliales[filliale] = [employee]
    return filliales

employees_salaries = monthly_salary()

mean_salary, max_salary, min_salary = calculate_statistics(employees_salaries)

print("\nStatistiques des salaires :")
print(f"Salaire moyen: {mean_salary:.2f}")
print(f"Salaire maximum: {max_salary:.2f}")
print(f"Salaire minimum: {min_salary:.2f}")

filliales = group_employees_by_filliale(employees_salaries)

print("\nEmployés par filliale :")
for filliale, employees in filliales.items():
    print(f"\nFilliale: {filliale}")
    for employee in employees:
        print(f" - {employee['name']} ({employee['job']}) : {employee['salary']:.2f}")

Helen                |Chef de projet       |2375.00
Quincy               |Testeur              |1456.00
Fred                 |Manager              |1815.00
Steve                |Chef de projet       |1600.00
Linda                |Chef de projet       |1700.00
Bob                  |Analyste             |1400.00
Steve                |Chef de projet       |2825.00
Karen                |Développeur          |1155.00
Paul                 |Designer             |900.00
Bob                  |Développeur          |1907.50
Bob                  |Manager              |2750.00
Mike                 |Testeur              |924.00
Mike                 |Chef de projet       |2225.00
Charlie              |Chef de projet       |1600.00
Helen                |Testeur              |1526.00
Jack                 |Analyste             |1520.00
Emma                 |Designer             |1020.00
Ian                  |Chef de projet       |1900.00
Tina                 |Testeur              |1526.00
Oliver               |Chef de projet       |2675.00
Jack                 |Designer             |990.00
Oliver               |Manager              |2612.50
Rachel               |Testeur              |1064.00
Ian                  |Testeur              |1288.00
Jack                 |Chef de projet       |1900.00
Rachel               |Analyste             |1280.00
Helen                |Développeur          |1330.00
George               |Développeur          |1050.00
Rachel               |Testeur              |1526.00
Emma                 |Chef de projet       |2375.00
Mike                 |Manager              |1760.00
Ian                  |Chef de projet       |2050.00
Bob                  |Chef de projet       |2500.00
Fred                 |Testeur              |1498.00
Mike                 |Développeur          |1120.00
Oliver               |Chef de projet       |1975.00
Tina                 |Manager              |2035.00
Linda                |Testeur              |1120.00
Rachel               |Designer             |1635.00
Bob                  |Manager              |2832.50
Steve                |Chef de projet       |2375.00
Jack                 |Chef de projet       |1550.00
Jack                 |Designer             |1545.00
Charlie              |Manager              |2530.00
Oliver               |Développeur          |1225.00
Nina                 |Analyste             |1900.00
Steve                |Designer             |1335.00
Linda                |Développeur          |1277.50
Jack                 |Testeur              |1442.00
Charlie              |Chef de projet       |2125.00

Statistiques des salaires :
Salaire moyen: 1720.90
Salaire maximum: 2832.50
Salaire minimum: 900.00

Employés par filliale :

Filliale: Inconnue
 - Helen (Chef de projet) : 2375.00
 - Quincy (Testeur) : 1456.00
 - Fred (Manager) : 1815.00
 - Steve (Chef de projet) : 1600.00
 - Linda (Chef de projet) : 1700.00
 - Bob (Analyste) : 1400.00
 - Steve (Chef de projet) : 2825.00
 - Karen (Développeur) : 1155.00
 - Paul (Designer) : 900.00
 - Bob (Développeur) : 1907.50
 - Bob (Manager) : 2750.00
 - Mike (Testeur) : 924.00
 - Mike (Chef de projet) : 2225.00
 - Charlie (Chef de projet) : 1600.00
 - Helen (Testeur) : 1526.00
 - Jack (Analyste) : 1520.00
 - Emma (Designer) : 1020.00
 - Ian (Chef de projet) : 1900.00
 - Tina (Testeur) : 1526.00
 - Oliver (Chef de projet) : 2675.00
 - Jack (Designer) : 990.00
 - Oliver (Manager) : 2612.50
 - Rachel (Testeur) : 1064.00
 - Ian (Testeur) : 1288.00
 - Jack (Chef de projet) : 1900.00
 - Rachel (Analyste) : 1280.00
 - Helen (Développeur) : 1330.00
 - George (Développeur) : 1050.00
 - Rachel (Testeur) : 1526.00
 - Emma (Chef de projet) : 2375.00
 - Mike (Manager) : 1760.00
 - Ian (Chef de projet) : 2050.00
 - Bob (Chef de projet) : 2500.00
 - Fred (Testeur) : 1498.00
 - Mike (Développeur) : 1120.00
 - Oliver (Chef de projet) : 1975.00
 - Tina (Manager) : 2035.00
 - Linda (Testeur) : 1120.00
 - Rachel (Designer) : 1635.00
 - Bob (Manager) : 2832.50
 - Steve (Chef de projet) : 2375.00
 - Jack (Chef de projet) : 1550.00
 - Jack (Designer) : 1545.00
 - Charlie (Manager) : 2530.00
 - Oliver (Développeur) : 1225.00
 - Nina (Analyste) : 1900.00
 - Steve (Designer) : 1335.00
 - Linda (Développeur) : 1277.50
 - Jack (Testeur) : 1442.00
 - Charlie (Chef de projet) : 2125.00

In [155]:
import json

def monthly_salary():
    with open('employes_data.json', 'r') as file_json:
        data_employees = json.load(file_json)

    def calculate_monthly_salary(employee):
        contract_hours = employee['contract_hours']
        weekly_hours_worked = employee['weekly_hours_worked']
        hourly_rate = employee['hourly_rate']

        if weekly_hours_worked > contract_hours:
            overtime_hours = weekly_hours_worked - contract_hours
            overtime_rate = hourly_rate * 1.5
            salary = contract_hours * hourly_rate + overtime_hours * overtime_rate
        else:
            salary = weekly_hours_worked * hourly_rate

        return salary

    def salary_employees():
        employees_salaries = []
        for filliale, employees in data_employees.items():
            for employee in employees:
                name = employee['name']
                job = employee['job']
                filliale = employee.get('filliale', 'Inconnue')  # Gestion de la filiale inconnue
                salary = calculate_monthly_salary(employee)
                employees_salaries.append({
                    'name': name,
                    'job': job,
                    'filliale': filliale,
                    'salary': salary
                })
        return employees_salaries
    
    employees_salaries = salary_employees()

    return employees_salaries

def group_employees_by_filliale(employees_salaries):
    filliales = {}
    for employee in employees_salaries:
        filliale = employee['filliale']
        if filliale in filliales:
            filliales[filliale].append(employee)
        else:
            filliales[filliale] = [employee]
    return filliales

# Running the salary calculation
employees_salaries = monthly_salary()

# Grouping employees by filiale
filliales = group_employees_by_filliale(employees_salaries)

# Creating and displaying a table for each filiale without using DataFrame
for filliale, employees in filliales.items():
    print(f"\nTableau des salaires pour la filiale: {filliale}")
    print(f"{'Nom':<20} {'Poste':<20} {'Salaire (€/mois)':<20}")
    print("-" * 60)
    for employee in employees:
        print(f"{employee['name']:<20} {employee['job']:<20} {employee['salary']:<20.2f}")
    print("-" * 60)

Tableau des salaires pour la filiale: Inconnue
Nom                  Poste                Salaire (€/mois)
------------------------------------------------------------
Helen                Chef de projet       2375.00
Quincy               Testeur              1456.00
Fred                 Manager              1815.00
Steve                Chef de projet       1600.00
Linda                Chef de projet       1700.00
Bob                  Analyste             1400.00
Steve                Chef de projet       2825.00
Karen                Développeur          1155.00
Paul                 Designer             900.00
Bob                  Développeur          1907.50
Bob                  Manager              2750.00
Mike                 Testeur              924.00
Mike                 Chef de projet       2225.00
Charlie              Chef de projet       1600.00
Helen                Testeur              1526.00
Jack                 Analyste             1520.00
Emma                 Designer             1020.00
Ian                  Chef de projet       1900.00
Tina                 Testeur              1526.00
Oliver               Chef de projet       2675.00
Jack                 Designer             990.00
Oliver               Manager              2612.50
Rachel               Testeur              1064.00
Ian                  Testeur              1288.00
Jack                 Chef de projet       1900.00
Rachel               Analyste             1280.00
Helen                Développeur          1330.00
George               Développeur          1050.00
Rachel               Testeur              1526.00
Emma                 Chef de projet       2375.00
Mike                 Manager              1760.00
Ian                  Chef de projet       2050.00
Bob                  Chef de projet       2500.00
Fred                 Testeur              1498.00
Mike                 Développeur          1120.00
Oliver               Chef de projet       1975.00
Tina                 Manager              2035.00
Linda                Testeur              1120.00
Rachel               Designer             1635.00
Bob                  Manager              2832.50
Steve                Chef de projet       2375.00
Jack                 Chef de projet       1550.00
Jack                 Designer             1545.00
Charlie              Manager              2530.00
Oliver               Développeur          1225.00
Nina                 Analyste             1900.00
Steve                Designer             1335.00
Linda                Développeur          1277.50
Jack                 Testeur              1442.00
Charlie              Chef de projet       2125.00
------------------------------------------------------------